<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class productmodel extends Model
{
    use HasFactory;

    protected $table="products";

    public $timestamps=false;
    protected $fillable=[
        'ProductName',
        'Quantity',
        'Price'
    ];

    public  function getRouteKeyName()
    {
        return 'ProductName'; // TODO: Change the autogenerated stub
    }
}
